version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-cognito-lambda-auth-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qc95h5vygm0u"
s3_prefix = "aws-cognito-lambda-auth-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
